
spring:
  application:
    name: zuul-server



server:
  port: 8762
   
    
zuul:
  ignored-services: '*'
  routes:
   user-registration-service: 
     path: /api/**
     service-id: user-registration-service

user-registration-service:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 1000
    ReadTimeout: 60000
    ConnectTimeout: 60000
    
user-search-delete-service:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 1000
    ReadTimeout: 60000
    ConnectTimeout: 60000


    
hystrix:
  command:
    user-registration-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
    user-search-delete-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 600000

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 40
    metadata-map:
      zone: zone1
    instance-id: ${spring.application.name}:${random.value}
  client:
    prefer-same-zone-eureka: true
    register-with-eureka: true
    fetch-registry: true
    region: region1
    service-url:
      zone1: http://eureka-server:8761/eureka/
    availability-zones:
      region1: zone1
    healthcheck:
      enabled: true      
 
