spring:
  application:
    name: cloud-api-gateway
  cloud:
     gateway:
       routes: 
         - predicates:
             - Path=/api/**
           filters:
              - StripPrefix=1
           uri: lb://user-registration-service
       discovery:
        locator:
          enabled: true
          lower-case-service-id: true
            
server:
  port: 8763
 
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
  client:
    prefer-same-zone-eureka: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    healthcheck:
      enabled: true    

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000
        
user-registration-service:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 60000
    ReadTimeout: 60000
    ConnectTimeout: 60000